/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TrishieldVaultRouteImport } from './routes/trishield-vault'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GiveExamRouteImport } from './routes/give-exam'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExamEntryRouteImport } from './routes/exam-entry'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminTrishieldReportsRouteImport } from './routes/superadmin.trishield-reports'
import { Route as SuperadminSystemRouteImport } from './routes/superadmin.system'
import { Route as SuperadminPaperLeakDetectorRouteImport } from './routes/superadmin.paper-leak-detector'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as SuperadminAuditLogRouteImport } from './routes/superadmin.audit-log'
import { Route as SuperadminAdminsRouteImport } from './routes/superadmin.admins'
import { Route as InvigilatorSeatingRouteImport } from './routes/invigilator.seating'
import { Route as InvigilatorLiveMonitorRouteImport } from './routes/invigilator.live-monitor'
import { Route as InvigilatorIncidentsRouteImport } from './routes/invigilator.incidents'
import { Route as InvigilatorDashboardRouteImport } from './routes/invigilator.dashboard'
import { Route as InvigilatorAttendanceRouteImport } from './routes/invigilator.attendance'
import { Route as InstituteDashboardRouteImport } from './routes/institute.dashboard'
import { Route as ExamRegistrationIdRouteImport } from './routes/exam.$registrationId'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CandidateResultsRouteImport } from './routes/candidate.results'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateNotificationsRouteImport } from './routes/candidate.notifications'
import { Route as CandidateExamsRouteImport } from './routes/candidate.exams'
import { Route as CandidateDashboardRouteImport } from './routes/candidate.dashboard'
import { Route as CandidateBillingRouteImport } from './routes/candidate.billing'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminIntegrityRouteImport } from './routes/admin.integrity'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCentersRouteImport } from './routes/admin.centers'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as ApiPublicGiveExamVerifyRouteImport } from './routes/api/public/give-exam-verify'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksCleanupSnapshotsRouteImport } from './routes/api/public/hooks/cleanup-snapshots'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TrishieldVaultRoute = TrishieldVaultRouteImport.update({
  id: '/trishield-vault',
  path: '/trishield-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveExamRoute = GiveExamRouteImport.update({
  id: '/give-exam',
  path: '/give-exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamEntryRoute = ExamEntryRouteImport.update({
  id: '/exam-entry',
  path: '/exam-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminTrishieldReportsRoute =
  SuperadminTrishieldReportsRouteImport.update({
    id: '/superadmin/trishield-reports',
    path: '/superadmin/trishield-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminSystemRoute = SuperadminSystemRouteImport.update({
  id: '/superadmin/system',
  path: '/superadmin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminPaperLeakDetectorRoute =
  SuperadminPaperLeakDetectorRouteImport.update({
    id: '/superadmin/paper-leak-detector',
    path: '/superadmin/paper-leak-detector',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/superadmin/dashboard',
  path: '/superadmin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminAuditLogRoute = SuperadminAuditLogRouteImport.update({
  id: '/superadmin/audit-log',
  path: '/superadmin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminAdminsRoute = SuperadminAdminsRouteImport.update({
  id: '/superadmin/admins',
  path: '/superadmin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const InvigilatorSeatingRoute = InvigilatorSeatingRouteImport.update({
  id: '/invigilator/seating',
  path: '/invigilator/seating',
  getParentRoute: () => rootRouteImport,
} as any)
const InvigilatorLiveMonitorRoute = InvigilatorLiveMonitorRouteImport.update({
  id: '/invigilator/live-monitor',
  path: '/invigilator/live-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const InvigilatorIncidentsRoute = InvigilatorIncidentsRouteImport.update({
  id: '/invigilator/incidents',
  path: '/invigilator/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const InvigilatorDashboardRoute = InvigilatorDashboardRouteImport.update({
  id: '/invigilator/dashboard',
  path: '/invigilator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvigilatorAttendanceRoute = InvigilatorAttendanceRouteImport.update({
  id: '/invigilator/attendance',
  path: '/invigilator/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const InstituteDashboardRoute = InstituteDashboardRouteImport.update({
  id: '/institute/dashboard',
  path: '/institute/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRegistrationIdRoute = ExamRegistrationIdRouteImport.update({
  id: '/exam/$registrationId',
  path: '/exam/$registrationId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateResultsRoute = CandidateResultsRouteImport.update({
  id: '/candidate/results',
  path: '/candidate/results',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateNotificationsRoute = CandidateNotificationsRouteImport.update({
  id: '/candidate/notifications',
  path: '/candidate/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateExamsRoute = CandidateExamsRouteImport.update({
  id: '/candidate/exams',
  path: '/candidate/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateBillingRoute = CandidateBillingRouteImport.update({
  id: '/candidate/billing',
  path: '/candidate/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrityRoute = AdminIntegrityRouteImport.update({
  id: '/admin/integrity',
  path: '/admin/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/admin/exams',
  path: '/admin/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCentersRoute = AdminCentersRouteImport.update({
  id: '/admin/centers',
  path: '/admin/centers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/admin/candidates',
  path: '/admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGiveExamVerifyRoute = ApiPublicGiveExamVerifyRouteImport.update({
  id: '/api/public/give-exam-verify',
  path: '/api/public/give-exam-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCleanupSnapshotsRoute =
  ApiPublicHooksCleanupSnapshotsRouteImport.update({
    id: '/api/public/hooks/cleanup-snapshots',
    path: '/api/public/hooks/cleanup-snapshots',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exam-entry': typeof ExamEntryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/give-exam': typeof GiveExamRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trishield-vault': typeof TrishieldVaultRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/integrity': typeof AdminIntegrityRoute
  '/admin/reports': typeof AdminReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/candidate/billing': typeof CandidateBillingRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/exams': typeof CandidateExamsRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/exam/$registrationId': typeof ExamRegistrationIdRoute
  '/institute/dashboard': typeof InstituteDashboardRoute
  '/invigilator/attendance': typeof InvigilatorAttendanceRoute
  '/invigilator/dashboard': typeof InvigilatorDashboardRoute
  '/invigilator/incidents': typeof InvigilatorIncidentsRoute
  '/invigilator/live-monitor': typeof InvigilatorLiveMonitorRoute
  '/invigilator/seating': typeof InvigilatorSeatingRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/audit-log': typeof SuperadminAuditLogRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/paper-leak-detector': typeof SuperadminPaperLeakDetectorRoute
  '/superadmin/system': typeof SuperadminSystemRoute
  '/superadmin/trishield-reports': typeof SuperadminTrishieldReportsRoute
  '/api/public/give-exam-verify': typeof ApiPublicGiveExamVerifyRoute
  '/api/public/hooks/cleanup-snapshots': typeof ApiPublicHooksCleanupSnapshotsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exam-entry': typeof ExamEntryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/give-exam': typeof GiveExamRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trishield-vault': typeof TrishieldVaultRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/integrity': typeof AdminIntegrityRoute
  '/admin/reports': typeof AdminReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/candidate/billing': typeof CandidateBillingRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/exams': typeof CandidateExamsRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/exam/$registrationId': typeof ExamRegistrationIdRoute
  '/institute/dashboard': typeof InstituteDashboardRoute
  '/invigilator/attendance': typeof InvigilatorAttendanceRoute
  '/invigilator/dashboard': typeof InvigilatorDashboardRoute
  '/invigilator/incidents': typeof InvigilatorIncidentsRoute
  '/invigilator/live-monitor': typeof InvigilatorLiveMonitorRoute
  '/invigilator/seating': typeof InvigilatorSeatingRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/audit-log': typeof SuperadminAuditLogRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/paper-leak-detector': typeof SuperadminPaperLeakDetectorRoute
  '/superadmin/system': typeof SuperadminSystemRoute
  '/superadmin/trishield-reports': typeof SuperadminTrishieldReportsRoute
  '/api/public/give-exam-verify': typeof ApiPublicGiveExamVerifyRoute
  '/api/public/hooks/cleanup-snapshots': typeof ApiPublicHooksCleanupSnapshotsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exam-entry': typeof ExamEntryRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/give-exam': typeof GiveExamRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trishield-vault': typeof TrishieldVaultRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/candidates': typeof AdminCandidatesRoute
  '/admin/centers': typeof AdminCentersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/integrity': typeof AdminIntegrityRoute
  '/admin/reports': typeof AdminReportsRoute
  '/api/chat': typeof ApiChatRoute
  '/candidate/billing': typeof CandidateBillingRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/exams': typeof CandidateExamsRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/exam/$registrationId': typeof ExamRegistrationIdRoute
  '/institute/dashboard': typeof InstituteDashboardRoute
  '/invigilator/attendance': typeof InvigilatorAttendanceRoute
  '/invigilator/dashboard': typeof InvigilatorDashboardRoute
  '/invigilator/incidents': typeof InvigilatorIncidentsRoute
  '/invigilator/live-monitor': typeof InvigilatorLiveMonitorRoute
  '/invigilator/seating': typeof InvigilatorSeatingRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/audit-log': typeof SuperadminAuditLogRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/superadmin/paper-leak-detector': typeof SuperadminPaperLeakDetectorRoute
  '/superadmin/system': typeof SuperadminSystemRoute
  '/superadmin/trishield-reports': typeof SuperadminTrishieldReportsRoute
  '/api/public/give-exam-verify': typeof ApiPublicGiveExamVerifyRoute
  '/api/public/hooks/cleanup-snapshots': typeof ApiPublicHooksCleanupSnapshotsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/exam-entry'
    | '/forgot-password'
    | '/give-exam'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/sitemap.xml'
    | '/trishield-vault'
    | '/verify-email'
    | '/admin/candidates'
    | '/admin/centers'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/integrity'
    | '/admin/reports'
    | '/api/chat'
    | '/candidate/billing'
    | '/candidate/dashboard'
    | '/candidate/exams'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/results'
    | '/checkout/return'
    | '/exam/$registrationId'
    | '/institute/dashboard'
    | '/invigilator/attendance'
    | '/invigilator/dashboard'
    | '/invigilator/incidents'
    | '/invigilator/live-monitor'
    | '/invigilator/seating'
    | '/superadmin/admins'
    | '/superadmin/audit-log'
    | '/superadmin/dashboard'
    | '/superadmin/paper-leak-detector'
    | '/superadmin/system'
    | '/superadmin/trishield-reports'
    | '/api/public/give-exam-verify'
    | '/api/public/hooks/cleanup-snapshots'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/exam-entry'
    | '/forgot-password'
    | '/give-exam'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/sitemap.xml'
    | '/trishield-vault'
    | '/verify-email'
    | '/admin/candidates'
    | '/admin/centers'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/integrity'
    | '/admin/reports'
    | '/api/chat'
    | '/candidate/billing'
    | '/candidate/dashboard'
    | '/candidate/exams'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/results'
    | '/checkout/return'
    | '/exam/$registrationId'
    | '/institute/dashboard'
    | '/invigilator/attendance'
    | '/invigilator/dashboard'
    | '/invigilator/incidents'
    | '/invigilator/live-monitor'
    | '/invigilator/seating'
    | '/superadmin/admins'
    | '/superadmin/audit-log'
    | '/superadmin/dashboard'
    | '/superadmin/paper-leak-detector'
    | '/superadmin/system'
    | '/superadmin/trishield-reports'
    | '/api/public/give-exam-verify'
    | '/api/public/hooks/cleanup-snapshots'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/exam-entry'
    | '/forgot-password'
    | '/give-exam'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap'
    | '/sitemap.xml'
    | '/trishield-vault'
    | '/verify-email'
    | '/admin/candidates'
    | '/admin/centers'
    | '/admin/dashboard'
    | '/admin/exams'
    | '/admin/integrity'
    | '/admin/reports'
    | '/api/chat'
    | '/candidate/billing'
    | '/candidate/dashboard'
    | '/candidate/exams'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/results'
    | '/checkout/return'
    | '/exam/$registrationId'
    | '/institute/dashboard'
    | '/invigilator/attendance'
    | '/invigilator/dashboard'
    | '/invigilator/incidents'
    | '/invigilator/live-monitor'
    | '/invigilator/seating'
    | '/superadmin/admins'
    | '/superadmin/audit-log'
    | '/superadmin/dashboard'
    | '/superadmin/paper-leak-detector'
    | '/superadmin/system'
    | '/superadmin/trishield-reports'
    | '/api/public/give-exam-verify'
    | '/api/public/hooks/cleanup-snapshots'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExamEntryRoute: typeof ExamEntryRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GiveExamRoute: typeof GiveExamRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrishieldVaultRoute: typeof TrishieldVaultRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminCandidatesRoute: typeof AdminCandidatesRoute
  AdminCentersRoute: typeof AdminCentersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminIntegrityRoute: typeof AdminIntegrityRoute
  AdminReportsRoute: typeof AdminReportsRoute
  ApiChatRoute: typeof ApiChatRoute
  CandidateBillingRoute: typeof CandidateBillingRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateExamsRoute: typeof CandidateExamsRoute
  CandidateNotificationsRoute: typeof CandidateNotificationsRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateResultsRoute: typeof CandidateResultsRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ExamRegistrationIdRoute: typeof ExamRegistrationIdRoute
  InstituteDashboardRoute: typeof InstituteDashboardRoute
  InvigilatorAttendanceRoute: typeof InvigilatorAttendanceRoute
  InvigilatorDashboardRoute: typeof InvigilatorDashboardRoute
  InvigilatorIncidentsRoute: typeof InvigilatorIncidentsRoute
  InvigilatorLiveMonitorRoute: typeof InvigilatorLiveMonitorRoute
  InvigilatorSeatingRoute: typeof InvigilatorSeatingRoute
  SuperadminAdminsRoute: typeof SuperadminAdminsRoute
  SuperadminAuditLogRoute: typeof SuperadminAuditLogRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
  SuperadminPaperLeakDetectorRoute: typeof SuperadminPaperLeakDetectorRoute
  SuperadminSystemRoute: typeof SuperadminSystemRoute
  SuperadminTrishieldReportsRoute: typeof SuperadminTrishieldReportsRoute
  ApiPublicGiveExamVerifyRoute: typeof ApiPublicGiveExamVerifyRoute
  ApiPublicHooksCleanupSnapshotsRoute: typeof ApiPublicHooksCleanupSnapshotsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trishield-vault': {
      id: '/trishield-vault'
      path: '/trishield-vault'
      fullPath: '/trishield-vault'
      preLoaderRoute: typeof TrishieldVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give-exam': {
      id: '/give-exam'
      path: '/give-exam'
      fullPath: '/give-exam'
      preLoaderRoute: typeof GiveExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-entry': {
      id: '/exam-entry'
      path: '/exam-entry'
      fullPath: '/exam-entry'
      preLoaderRoute: typeof ExamEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/trishield-reports': {
      id: '/superadmin/trishield-reports'
      path: '/superadmin/trishield-reports'
      fullPath: '/superadmin/trishield-reports'
      preLoaderRoute: typeof SuperadminTrishieldReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/system': {
      id: '/superadmin/system'
      path: '/superadmin/system'
      fullPath: '/superadmin/system'
      preLoaderRoute: typeof SuperadminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/paper-leak-detector': {
      id: '/superadmin/paper-leak-detector'
      path: '/superadmin/paper-leak-detector'
      fullPath: '/superadmin/paper-leak-detector'
      preLoaderRoute: typeof SuperadminPaperLeakDetectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/audit-log': {
      id: '/superadmin/audit-log'
      path: '/superadmin/audit-log'
      fullPath: '/superadmin/audit-log'
      preLoaderRoute: typeof SuperadminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/admins': {
      id: '/superadmin/admins'
      path: '/superadmin/admins'
      fullPath: '/superadmin/admins'
      preLoaderRoute: typeof SuperadminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invigilator/seating': {
      id: '/invigilator/seating'
      path: '/invigilator/seating'
      fullPath: '/invigilator/seating'
      preLoaderRoute: typeof InvigilatorSeatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invigilator/live-monitor': {
      id: '/invigilator/live-monitor'
      path: '/invigilator/live-monitor'
      fullPath: '/invigilator/live-monitor'
      preLoaderRoute: typeof InvigilatorLiveMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invigilator/incidents': {
      id: '/invigilator/incidents'
      path: '/invigilator/incidents'
      fullPath: '/invigilator/incidents'
      preLoaderRoute: typeof InvigilatorIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invigilator/dashboard': {
      id: '/invigilator/dashboard'
      path: '/invigilator/dashboard'
      fullPath: '/invigilator/dashboard'
      preLoaderRoute: typeof InvigilatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invigilator/attendance': {
      id: '/invigilator/attendance'
      path: '/invigilator/attendance'
      fullPath: '/invigilator/attendance'
      preLoaderRoute: typeof InvigilatorAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institute/dashboard': {
      id: '/institute/dashboard'
      path: '/institute/dashboard'
      fullPath: '/institute/dashboard'
      preLoaderRoute: typeof InstituteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$registrationId': {
      id: '/exam/$registrationId'
      path: '/exam/$registrationId'
      fullPath: '/exam/$registrationId'
      preLoaderRoute: typeof ExamRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/results': {
      id: '/candidate/results'
      path: '/candidate/results'
      fullPath: '/candidate/results'
      preLoaderRoute: typeof CandidateResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/notifications': {
      id: '/candidate/notifications'
      path: '/candidate/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof CandidateNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/exams': {
      id: '/candidate/exams'
      path: '/candidate/exams'
      fullPath: '/candidate/exams'
      preLoaderRoute: typeof CandidateExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/billing': {
      id: '/candidate/billing'
      path: '/candidate/billing'
      fullPath: '/candidate/billing'
      preLoaderRoute: typeof CandidateBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrity': {
      id: '/admin/integrity'
      path: '/admin/integrity'
      fullPath: '/admin/integrity'
      preLoaderRoute: typeof AdminIntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/centers': {
      id: '/admin/centers'
      path: '/admin/centers'
      fullPath: '/admin/centers'
      preLoaderRoute: typeof AdminCentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/give-exam-verify': {
      id: '/api/public/give-exam-verify'
      path: '/api/public/give-exam-verify'
      fullPath: '/api/public/give-exam-verify'
      preLoaderRoute: typeof ApiPublicGiveExamVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-snapshots': {
      id: '/api/public/hooks/cleanup-snapshots'
      path: '/api/public/hooks/cleanup-snapshots'
      fullPath: '/api/public/hooks/cleanup-snapshots'
      preLoaderRoute: typeof ApiPublicHooksCleanupSnapshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExamEntryRoute: ExamEntryRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GiveExamRoute: GiveExamRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrishieldVaultRoute: TrishieldVaultRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminCandidatesRoute: AdminCandidatesRoute,
  AdminCentersRoute: AdminCentersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminIntegrityRoute: AdminIntegrityRoute,
  AdminReportsRoute: AdminReportsRoute,
  ApiChatRoute: ApiChatRoute,
  CandidateBillingRoute: CandidateBillingRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateExamsRoute: CandidateExamsRoute,
  CandidateNotificationsRoute: CandidateNotificationsRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateResultsRoute: CandidateResultsRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ExamRegistrationIdRoute: ExamRegistrationIdRoute,
  InstituteDashboardRoute: InstituteDashboardRoute,
  InvigilatorAttendanceRoute: InvigilatorAttendanceRoute,
  InvigilatorDashboardRoute: InvigilatorDashboardRoute,
  InvigilatorIncidentsRoute: InvigilatorIncidentsRoute,
  InvigilatorLiveMonitorRoute: InvigilatorLiveMonitorRoute,
  InvigilatorSeatingRoute: InvigilatorSeatingRoute,
  SuperadminAdminsRoute: SuperadminAdminsRoute,
  SuperadminAuditLogRoute: SuperadminAuditLogRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
  SuperadminPaperLeakDetectorRoute: SuperadminPaperLeakDetectorRoute,
  SuperadminSystemRoute: SuperadminSystemRoute,
  SuperadminTrishieldReportsRoute: SuperadminTrishieldReportsRoute,
  ApiPublicGiveExamVerifyRoute: ApiPublicGiveExamVerifyRoute,
  ApiPublicHooksCleanupSnapshotsRoute: ApiPublicHooksCleanupSnapshotsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
