/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as InvigilatorDashboardRouteImport } from './routes/invigilator.dashboard'
import { Route as CandidateResultsRouteImport } from './routes/candidate.results'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateNotificationsRouteImport } from './routes/candidate.notifications'
import { Route as CandidateExamsRouteImport } from './routes/candidate.exams'
import { Route as CandidateDashboardRouteImport } from './routes/candidate.dashboard'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/superadmin/dashboard',
  path: '/superadmin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvigilatorDashboardRoute = InvigilatorDashboardRouteImport.update({
  id: '/invigilator/dashboard',
  path: '/invigilator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateResultsRoute = CandidateResultsRouteImport.update({
  id: '/candidate/results',
  path: '/candidate/results',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateNotificationsRoute = CandidateNotificationsRouteImport.update({
  id: '/candidate/notifications',
  path: '/candidate/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateExamsRoute = CandidateExamsRouteImport.update({
  id: '/candidate/exams',
  path: '/candidate/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/exams': typeof CandidateExamsRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/invigilator/dashboard': typeof InvigilatorDashboardRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/exams': typeof CandidateExamsRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/invigilator/dashboard': typeof InvigilatorDashboardRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/exams': typeof CandidateExamsRoute
  '/candidate/notifications': typeof CandidateNotificationsRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/results': typeof CandidateResultsRoute
  '/invigilator/dashboard': typeof InvigilatorDashboardRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/dashboard'
    | '/candidate/dashboard'
    | '/candidate/exams'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/results'
    | '/invigilator/dashboard'
    | '/superadmin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/dashboard'
    | '/candidate/dashboard'
    | '/candidate/exams'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/results'
    | '/invigilator/dashboard'
    | '/superadmin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/admin/dashboard'
    | '/candidate/dashboard'
    | '/candidate/exams'
    | '/candidate/notifications'
    | '/candidate/profile'
    | '/candidate/results'
    | '/invigilator/dashboard'
    | '/superadmin/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateExamsRoute: typeof CandidateExamsRoute
  CandidateNotificationsRoute: typeof CandidateNotificationsRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateResultsRoute: typeof CandidateResultsRoute
  InvigilatorDashboardRoute: typeof InvigilatorDashboardRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invigilator/dashboard': {
      id: '/invigilator/dashboard'
      path: '/invigilator/dashboard'
      fullPath: '/invigilator/dashboard'
      preLoaderRoute: typeof InvigilatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/results': {
      id: '/candidate/results'
      path: '/candidate/results'
      fullPath: '/candidate/results'
      preLoaderRoute: typeof CandidateResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/notifications': {
      id: '/candidate/notifications'
      path: '/candidate/notifications'
      fullPath: '/candidate/notifications'
      preLoaderRoute: typeof CandidateNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/exams': {
      id: '/candidate/exams'
      path: '/candidate/exams'
      fullPath: '/candidate/exams'
      preLoaderRoute: typeof CandidateExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateExamsRoute: CandidateExamsRoute,
  CandidateNotificationsRoute: CandidateNotificationsRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateResultsRoute: CandidateResultsRoute,
  InvigilatorDashboardRoute: InvigilatorDashboardRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
